python train_decoder.py \
  --data-root data/replay_buffer.zarr \
  --vision-key image \
  --wm-ckpt-path logs/ckpts/image_dino_vit/100000.ckpt \
  --encoder-type dino \
  --predictor-type vit \
  --dino-name dinov2_vits14 \
  --image-size 224 \
  --num-steps 5 \
  --batch-size 32 \
  --epochs 200